title: "Data Science Portfolio"
description: "Showcasing my Data Science projects and skills"
theme: jekyll-theme-minimal  # Change this to match your actual theme
show_downloads: false
is_project_page: true
